### ISSUE TITLE
No more working with Homey firmware 6.0.0rc4 and above

### ISSUE THREAD

**Issue by alechenne** [magohl/com.husqvarna.automower#8]
Dear all,

First of all, many thanks for that app, I installed it and have used it for few weeks. It seems to work fine. But few days ago, I cannot connect anymore with the automower. I tried to restart the Homey app, but was always in trouble (cannot connect via the API I guess). 

I was running the Homey firmware 6.0.0-rc.4 (and now 6.0.0-rc.5). I'm not sure if it's depending of the firmware or the API (I read the API docs and tried to connect wia postman and got some error "scope not defined" even if I provided the rigth info (API key, ...).

I removed the Homey app and resinstall it again. When I want to re-install the automower,  after click on "connect", I got the following error: "cannot read 'data' of undefined.

Thanks in advance for your support.

Kind regards

**Comment by magohl** [comment]
I have not yet tried the 6.0.0-rc's myself but as you seem to have problems using the API directly that might not be the issue.

Two things i would look into:

- Myself and others have had problems entering the credentials on the Homey App Settings using a mobile device. When copy/pasting there sometimes seem to be a space in the end of the email or password field that is hard to detect. Try entering the credentials on a PC using the page https://developer.athom.com/tools/app-settings in favor of the Homey mobile application.

- Make sure your "Husqvarna Developer" application has both APIs connected. Your error 'scope not defined' could be an indication to this. Look in https://developer.husqvarnagroup.cloud/apps and make sure both the 'Authentication API' and the 'Automower Conect API' are selected/connected.

**Comment by magohl** [comment]
I have now tried using Homey Firmware 6.0.0 and the app does seem to behave and work exactly as before.

@alechenne - please have a look at the two suggestions above and let me know how that works out. If it is still not working we will just have to do a bit more troubleshooting.

**Comment by magohl** [comment]
Hi @alechenne, did you manage to get it to work again?

**Comment by alechenne** [comment]
> I have not yet tried the 6.0.0-rc's myself but as you seem to have problems using the API directly that might not be the issue.
> 
> Two things i would look into:
> 
> * Myself and others have had problems entering the credentials on the Homey App Settings using a mobile device. When copy/pasting there sometimes seem to be a space in the end of the email or password field that is hard to detect. Try entering the credentials on a PC using the page https://developer.athom.com/tools/app-settings in favor of the Homey mobile application.
> * Make sure your "Husqvarna Developer" application has both APIs connected. Your error 'scope not defined' could be an indication to this. Look in https://developer.husqvarnagroup.cloud/apps and make sure both the 'Authentication API' and the 'Automower Conect API' are selected/connected. Also see #4 where another user had this exact problem.

Sorry for the delay of my reply but I was very busy with my job during the last 2 weeks.

I double check the credentials in the Homey App Settings and this the right username, password and API key (I sign out from the Husqvarna space and sign in again to be sure I use the same username and pwd in the Hpomey App settings). I also removed the Homey App and re-installed it. I also created a new app in the Husqvarna dev space and a new API key, but I always get the same error.

I alse tried to update to the last Homey firmware 6.1.0 rc2, but witjout more success. I will check the other same issue (#4) you mention to check if there is something I still not have done.

**Comment by alechenne** [comment]
> > I have not yet tried the 6.0.0-rc's myself but as you seem to have problems using the API directly that might not be the issue.
> > Two things i would look into:
> > 
> > * Myself and others have had problems entering the credentials on the Homey App Settings using a mobile device. When copy/pasting there sometimes seem to be a space in the end of the email or password field that is hard to detect. Try entering the credentials on a PC using the page https://developer.athom.com/tools/app-settings in favor of the Homey mobile application.
> > * Make sure your "Husqvarna Developer" application has both APIs connected. Your error 'scope not defined' could be an indication to this. Look in https://developer.husqvarnagroup.cloud/apps and make sure both the 'Authentication API' and the 'Automower Conect API' are selected/connected. Also see #4 where another user had this exact problem.
> 
> Sorry for the delay of my reply but I was very busy with my job during the last 2 weeks.
> 
> I double check the credentials in the Homey App Settings and this the right username, password and API key (I sign out from the Husqvarna space and sign in again to be sure I use the same username and pwd in the Hpomey App settings). I also removed the Homey App and re-installed it. I also created a new app in the Husqvarna dev space and a new API key, but I always get the same error.
> 
> I alse tried to update to the last Homey firmware 6.1.0 rc2, but witjout more success. I will check the other same issue (#4) you mention to check if there is something I still not have done.

Ok I found a way to correct the issue I have:

- Delete all the applications in the Husqvarna platform (https://developer.husqvarnagroup.cloud/apps)
- Create a new one; don't forget to connect the API "Authentication API" and the API "Automower Connect API"
- Sign out and sign in again in order to be sure to have the right username and pwd
- Copy the APPKEY
- In Homey App, in the "..." / App / Husqvarna, re-enter the credentials (username, pwd and APPKEY)
- Restart the Homey Husqvarna App
- In device, add a new Husqvarna

It should be good if you follow these steps. 

Don't to adapt the APPKEY in other apps you have developed as by deleting the App in the Husqvarna dev platform, you'll get another APPKEY!

**Comment by alechenne** [comment]
See previous comment for the solution.
